spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectinfo_sys?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
mybatis:
  #  扫描数据持久对应的实体类 路径 Package级别
  type-aliases-package: org.test.projectmanagement.Model
  #  mybatis 对应的 .xml文件路径
  mapper-locations: classpath:mapper/*.xml

